% run("Figure2_population_Reg_vs_Irreg.m");
run("Figure3_population_Diff_ICI.m");
run("Figure4_population_ICIThr.m");
run("Figure5_population_IrregVar.m");
run("Figure7_population_Duration.m");
run("Sfigure2_population_No_Reg_In_Irreg.m");
run("Sfigure2_population_Norm_Sqrt.m");
run("Sfigure2_population_Tone.m");
run("Sfigure5_population_IrregVar50_2.m");
run("Figure6_population_Oscillation.m");
run("Sfigure6_population_Oscillation_Tone.m");